spring:
  redis:
    host: dccore-dev-dbcc.c88wn7.0001.apne1.cache.amazonaws.com
    port: 6379
tomcat:
  ajp:
    enabled: true
    port: 8009
emptymail:
   domain: disney.jp
   account:
      prefix: SPPLOGIN+