spring:
  redis:
    host: dccore-dbcc.c88wn7.ng.0001.apne1.cache.amazonaws.com
    port: 6379
tomcat:
  ajp:
    enabled: true
    port: 8009
spplogin:
  emptymail:
    domain: mail.disney.jp
    session-coop-key:
      expire: 24
      expire-timeunit: HOURS
  core-webapi:
    proxy:
      enable: false
    base-url: http://localhost
    port: 80
    cor-901:
      redirect-url: https://ssopen.disney.co.jp/auidauth/SessionKeyInfoUpd/