# Thymeleaf
spring:
  thymeleaf:
    cache: false
# Redis
  redis:
    host: 127.0.0.1
    port: 6379
# Tomcat AJP Connection
tomcat:
  ajp:
    enabled: true
    port: 8009

spplogin:
  # 空メール関連
  emptymail:
    session-coop-key:
      expire: 10
      expire-timeunit: MINUTES