# 稼働環境の指定はサーバ環境変数(SPRING_PROFILES_ACTIVE)で設定する。
#spring:
#  profiles:
#    active: local

spring:
# Thymeleaf
  thymeleaf:
    enabled: true
    cache: true
# Redis
  redis:
    host: 127.0.0.1
    port: 6379
# INTERNATIONALIZATION
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
server:
   port: 8080
   context-path: /spplogin
   