spring:
  redis:
    host: dccore-stg-dbcc.c88wn7.0001.apne1.cache.amazonaws.com
    port: 6379
tomcat:
  ajp:
    enabled: true
    port: 8009
spplogin:
  base-url: https://stg.ssapi.disney.co.jp/spplogin/
  emptymail:
    domain: stg.msg.disney.co.jp
    session-coop-key:
      expire: 30
      expire-timeunit: MINUTES
  core-webapi:
    proxy:
      enable: false
    base-url: https://stg.ssopen.disney.co.jp
    port: 80
    cor-901:
      redirect-url: https://staging.ssopen.disney.co.jp/auidauth/SessionKeyInfoUpd/