spring:
  redis:
    host: dccore-dev-dbcc.c88wn7.0001.apne1.cache.amazonaws.com
    port: 6379
tomcat:
  ajp:
    enabled: true
    port: 8009
spplogin:
  emptymail:
    domain: dev.msg.disney.co.jp
    session-coop-key:
      expire: 10
      expire-timeunit: MINUTES
  core-webapi:
    proxy:
      enable: false
    base-url: http://dev.ssapi.disney.co.jp/spplogin/
    port: 80
    cor-901:
      redirect-url: http://dev.ssopen.disney.co.jp/auidauth/SessionKeyInfoUpd/