spring:
  profiles.active: local
# Thymeleaf
  thymeleaf:
    enabled: true
    cache: true
# Redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
   port: 8080
   context-path: /spplogin
   
