spring:
  redis:
    host: dccore-dev-dbcc.c88wn7.0001.apne1.cache.amazonaws.com
    port: 6379
tomcat:
  ajp:
    enabled: true
    port: 8009
emptymail:
   domain: disney.jp
   account:
      prefix: SPPLOGIN+
spplogin:
  base-url: http://dev.ssapi.disney.co.jp/spplogin/
  core-webapi:
    proxy:
      enable: false
    base-url: http://localhost
    port: 80
    cor-901:
      redirect-url: http://dev.ssopen.disney.co.jp/auidauth/SessionKeyInfoUpd/