# 稼働環境の指定はサーバ環境変数(SPRING_PROFILES_ACTIVE)で設定する。
#spring:
#  profiles:
#    active: local

spring:
# Thymeleaf
  thymeleaf:
    enabled: true
    cache: true
# Redis
  redis:
    host: 127.0.0.1
    port: 6379
# INTERNATIONALIZATION
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
# Mail
  mail:
    host: localhost
    port: 25
  velocity:
    enabled: false
server:
   port: 8080
   context-path: /spplogin
   session:
     timeout: 3600
# アプリ固有設定
spplogin:
  base-url: http://localhost:8080/spplogin/
  # 空メール関連
  emptymail:
    session-coop-key:
      prefix: a1
      expire: 24
      expire-timeunit: HOURS
    domain: mail.disney.jp
    account-prefix: spplogin-account
    account-separator: _
    auto-reply:
      from-address: spplogin-register@mail.disney.jp
      subject: 【ディズニーシェア】新規メンバー登録
  # CORE WebAPI関連
  core-webapi:
    proxy:
      enable: false
      schema: http
      host: ctcpro.ctc-g.co.jp
      port: 8080
      user: z2h7273
      password: unSrf93!
    base-url: http://dev.ssopen.disney.co.jp
    port: 80
    # COR-901 認証認可要求
    cor-901:
      path: /connect/authorize
      redirect-url: http://dev.ssopen.disney.co.jp/auidauth/SessionKeyInfoUpd/
      client-id: dshar_aL7foR2yEn
      nonce: n-0S6_WzA2Mj
      response-type: "code id_token"
      scope: openid
    # COR-112 DID会員情報照会
    cor-112:
      path: /webapi/v1/did/DIDInformation/me
    # COR-001 SPP会員新規登録
    cor-001:
      path: /webapi/v1/SPPMembership

    